### ISSUE TITLE
'socket' object has no attribute 'last_seen_sni'

### ISSUE THREAD

**Issue by bnavigator** [geventhttpclient/geventhttpclient#137]
Testing 1.4.5 on openSUSE Tumbleweed results in the following test failures:

```
[    6s] =================================== FAILURES ===================================
[    6s] ______________________ test_implicit_sni_from_host_in_ssl ______________________
[    6s] 
[    6s]     def test_implicit_sni_from_host_in_ssl():
[    6s] >       server_host, server_port, sent_sni = _get_sni_sent_from_client()
[    6s] 
[    6s] src/geventhttpclient/tests/test_ssl.py:92: 
[    6s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[    6s] src/geventhttpclient/tests/test_ssl.py:110: in _get_sni_sent_from_client
[    6s]     with sni_checker_server() as ctx:
[    6s] /usr/lib64/python3.8/contextlib.py:113: in __enter__
[    6s]     return next(self.gen)
[    6s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[    6s] 
[    6s]     @contextmanager
[    6s]     def sni_checker_server():
[    6s]         sock = gevent.socket.socket(gevent.socket.AF_INET,
[    6s]             gevent.socket.SOCK_STREAM, 0)
[    6s]         sock.setsockopt(gevent.socket.SOL_SOCKET, gevent.socket.SO_REUSEADDR, 1)
[    6s]         sock.bind(("localhost", 0))
[    6s]         sock.listen(1)
[    6s]     
[    6s] >       sock.last_seen_sni = None
[    6s] E       AttributeError: 'socket' object has no attribute 'last_seen_sni'
[    6s] 
[    6s] src/geventhttpclient/tests/test_ssl.py:157: AttributeError
[    6s] _____________________ test_implicit_sni_from_header_in_ssl _____________________
[    6s] 
[    6s]     def test_implicit_sni_from_header_in_ssl():
[    6s] >       server_host, server_port, sent_sni = _get_sni_sent_from_client(
[    6s]             headers={'host': 'ololo_special_host'},
[    6s]         )
[    6s] 
[    6s] src/geventhttpclient/tests/test_ssl.py:96: 
[    6s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[    6s] src/geventhttpclient/tests/test_ssl.py:110: in _get_sni_sent_from_client
[    6s]     with sni_checker_server() as ctx:
[    6s] /usr/lib64/python3.8/contextlib.py:113: in __enter__
[    6s]     return next(self.gen)
[    6s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[    6s] 
[    6s]     @contextmanager
[    6s]     def sni_checker_server():
[    6s]         sock = gevent.socket.socket(gevent.socket.AF_INET,
[    6s]             gevent.socket.SOCK_STREAM, 0)
[    6s]         sock.setsockopt(gevent.socket.SOL_SOCKET, gevent.socket.SO_REUSEADDR, 1)
[    6s]         sock.bind(("localhost", 0))
[    6s]         sock.listen(1)
[    6s]     
[    6s] >       sock.last_seen_sni = None
[    6s] E       AttributeError: 'socket' object has no attribute 'last_seen_sni'
[    6s] 
[    6s] src/geventhttpclient/tests/test_ssl.py:157: AttributeError
[    6s] ___________________________ test_explicit_sni_in_ssl ___________________________
[    6s] 
[    6s]     def test_explicit_sni_in_ssl():
[    6s] >       server_host, server_port, sent_sni = _get_sni_sent_from_client(
[    6s]             ssl_options={'server_hostname': 'test_sni'},
[    6s]             headers={'host': 'ololo_special_host'},
[    6s]         )
[    6s] 
[    6s] src/geventhttpclient/tests/test_ssl.py:102: 
[    6s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[    6s] src/geventhttpclient/tests/test_ssl.py:110: in _get_sni_sent_from_client
[    6s]     with sni_checker_server() as ctx:
[    6s] /usr/lib64/python3.8/contextlib.py:113: in __enter__
[    6s]     return next(self.gen)
[    6s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[    6s] 
[    6s]     @contextmanager
[    6s]     def sni_checker_server():
[    6s]         sock = gevent.socket.socket(gevent.socket.AF_INET,
[    6s]             gevent.socket.SOCK_STREAM, 0)
[    6s]         sock.setsockopt(gevent.socket.SOL_SOCKET, gevent.socket.SO_REUSEADDR, 1)
[    6s]         sock.bind(("localhost", 0))
[    6s]         sock.listen(1)
[    6s]     
[    6s] >       sock.last_seen_sni = None
[    6s] E       AttributeError: 'socket' object has no attribute 'last_seen_sni'
[    6s] 
[    6s] src/geventhttpclient/tests/test_ssl.py:157: AttributeError
[    6s] =========================== short test summary info ============================
[    6s] FAILED src/geventhttpclient/tests/test_ssl.py::test_implicit_sni_from_host_in_ssl
[    6s] FAILED src/geventhttpclient/tests/test_ssl.py::test_implicit_sni_from_header_in_ssl
[    6s] FAILED src/geventhttpclient/tests/test_ssl.py::test_explicit_sni_in_ssl - Att...
[    6s] ================= 3 failed, 75 passed, 13 deselected in 1.44s ==================
```

Python 3.8.7 and  3.6.12
gevent 21.1.2
greenlet 1.0.0

Full buildlog with all package versions: 
[geventhttpclient_log.txt](https://github.com/gwik/geventhttpclient/files/5989405/geventhttpclient_log.txt)

Removing this line lets the tests pass:
https://github.com/gwik/geventhttpclient/blob/94411973bbe539d87e5f611a432c2ecde3f55cae/src/geventhttpclient/tests/test_ssl.py#L157

**Comment by Apteryks** [comment]
I have the same issue after upgrading gevent from 0.4.17 to 1.0.0.

**Comment by ml31415** [comment]
Since python3.6 and python3.8 aren't supported anymore, I'm closing this issue. It doesn't seem to be reproducible with recent python / gevent. Feel free to reopen, if should still pop up somehow.
